# Generated by Django 5.2.7 on 2026-07-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('role', models.CharField(max_length=100, verbose_name='Rol / Posición')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('image', models.ImageField(upload_to='members/', verbose_name='Foto Teaser')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Mostrar en el Roster?')),
            ],
            options={
                'verbose_name': 'Integrante',
                'verbose_name_plural': 'Integrantes',
                'ordering': ['order', 'name'],
            },
        ),
    ]
