# Generated by Django 5.2.7 on 2026-07-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
        migrations.AddField(
            model_name='member',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='members/back/', verbose_name='Foto Reverso (Back)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(upload_to='members/', verbose_name='Foto Teaser (Frente)'),
        ),
    ]
