# Generated by Django 5.2.7 on 2026-07-22 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del álbum')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Fecha de lanzamiento')),
                ('album_type', models.CharField(choices=[('mini', 'Mini Album'), ('single', 'Single'), ('japanese', 'Japanese Release'), ('special', 'Special')], default='mini', max_length=20, verbose_name='Tipo de lanzamiento')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='albums/', verbose_name='Portada del álbum')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Álbum',
                'verbose_name_plural': 'Álbumes',
                'ordering': ['-release_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título de la Canción')),
                ('energy', models.CharField(choices=[('high', '⚡ Alta / Potente'), ('medium', '🎧 Media / Balanceada'), ('low', '🌙 Tranquila / Chill')], max_length=10, verbose_name='Nivel de Energía')),
                ('vibe_tags', models.TextField(help_text='Ej: oscuro, epico, divertido, emocional', verbose_name='Vibra / Tags')),
                ('mood_keywords', models.TextField(blank=True, help_text='Ej: feliz, bailar, motivación, noche, energía', verbose_name='Palabras clave de Kimiko')),
                ('kimiko_review', models.TextField(help_text='Mensaje que dirá Kimiko al recomendar esta canción.', verbose_name='Recomendación de Kimiko')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='Link de YouTube / MV')),
                ('spotify_url', models.URLField(blank=True, null=True, verbose_name='Link de Spotify')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='songs/', verbose_name='Portada individual')),
                ('song_type', models.CharField(blank=True, help_text='Ej: title track, b-side, intro, special', max_length=50, verbose_name='Tipo de canción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music_bot.album', verbose_name='Álbum')),
            ],
            options={
                'verbose_name': 'Canción',
                'verbose_name_plural': 'Canciones',
                'ordering': ['album__name', 'title'],
            },
        ),
    ]
