# Generated by Django 5.2.7 on 2026-07-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=50)),
                ('real_name', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField()),
                ('position', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='members/')),
                ('bio', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
