# Generated by Django 5.2.7 on 2026-07-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='favorite_color',
            field=models.CharField(choices=[('#E63946', 'Rojo'), ('#FFD21F', 'Amarillo'), ('#147DFF', 'Azul'), ('#2ECC71', 'Verde'), ('#9B59B6', 'Morado'), ('#F5F5F5', 'Blanco')], default='#FFD21F', max_length=7),
        ),
    ]
