# Generated by Django 5.2.7 on 2026-07-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_favorite_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='secondary_photo',
            field=models.ImageField(blank=True, help_text='Imagen o detalle para el espacio recuadrado a la izquierda', null=True, upload_to='members/secondary/'),
        ),
    ]
