# Generated by Django 5.2.7 on 2026-07-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_secondary_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='thumbnail_photo',
            field=models.ImageField(blank=True, help_text='Foto cuadrada pequeña para la ficha de la izquierda.', null=True, upload_to='members/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='secondary_photo',
            field=models.ImageField(blank=True, help_text='Imagen o detalle para el espacio recuadrado a la izquierda (gráfica de fondo)', null=True, upload_to='members/secondary/'),
        ),
    ]
